"use client";
import { useCallback, useEffect, useState } from "react";
type Incident = { id: number; reporterId: string; category: string; description: string; status: string; resolution: string; internalNotes?: string; revision: number };
export function IncidentManager({ admin = false }: { admin?: boolean }) {
  const [rows, setRows] = useState<Incident[]>([]), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const r = await fetch("/api/incidents" + (admin ? "?admin=1" : "")); const d = await r.json(); if (!r.ok) throw new Error(d.error); setRows(d.incidents); }, [admin]);
  // load only updates state after its network request resolves.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load().catch(e => setMessage(e.message)); }, [load]);
  async function send(data: unknown, method: string) { setBusy(true); try { const r = await fetch("/api/incidents", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); setMessage("Report saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Request failed."); } finally { setBusy(false); } }
  return <section className="grid gap-5"><h1 className="text-3xl font-bold">Incident reports</h1><p>For immediate danger, contact local emergency services. This inbox is not monitored continuously. Do not include sensitive information about children or residents.</p><p role="status">{message}</p>{!admin && <form className="grid gap-3 rounded border p-5" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void send({ category: f.get("category"), description: f.get("description") }, "POST"); }}><label>Category <select name="category" className="border p-2"><option value="food_safety">Food safety</option><option value="missed_pickup">Missed pickup</option><option value="misconduct">Misconduct</option><option value="other">Other</option></select></label><label className="grid">What happened? Include a donation number if relevant.<textarea name="description" minLength={10} maxLength={3000} required className="border p-3" /></label><button disabled={busy} className="rounded bg-[#153f3a] p-3 text-white">Submit report</button></form>}{rows.length === 0 && <p>No reports yet.</p>}{rows.map(row => <article key={row.id} className="grid gap-3 rounded border bg-white p-5"><h2 className="font-bold">#{row.id} · {row.category} · {row.status}</h2><p className="whitespace-pre-wrap">{row.description}</p>{row.resolution && <p>Response: {row.resolution}</p>}{admin && <form className="grid gap-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void send({ id: row.id, revision: row.revision, status: f.get("status"), resolution: f.get("resolution"), internalNotes: f.get("internalNotes") }, "PATCH"); }}><p>Reporter: {row.reporterId}</p><label>Status <select name="status" defaultValue={row.status}><option>open</option><option>investigating</option><option>resolved</option></select></label><label className="grid">Response visible to reporter<textarea name="resolution" defaultValue={row.resolution} maxLength={2000} className="border p-2" /></label><label className="grid">Private administrator notes<textarea name="internalNotes" defaultValue={row.internalNotes} maxLength={3000} className="border p-2" /></label><button disabled={busy}>Save case</button></form>}</article>)}<p>Showing the latest 100 reports.</p></section>;
}
