"use client";
import { useEffect, useState } from "react";
type State = { privacy: { userId: string; status: string }[]; deliveries: { id: number; userId: string; channel: string; status: string; attempts: number; lastError: string | null }[] };
export function OperationsManager() {
  const [state, setState] = useState<State | null>(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  async function load() { const r = await fetch("/api/admin/operations"), d = await r.json(); if (!r.ok) throw new Error(d.error); setState(d); }
  // load only updates state after its network request resolves.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load().catch(e => setMessage(e.message)); }, []);
  async function action(data: unknown) { setBusy(true); try { const r = await fetch("/api/admin/operations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); setMessage("Operation completed."); } catch (e) { setMessage(e instanceof Error ? e.message : "Operation failed."); } finally { setBusy(false); } }
  return <section className="grid gap-6"><h1 className="text-3xl font-bold">Privacy & notification operations</h1><p role="status">{message}</p><button onClick={() => load().catch(e => setMessage(e.message))}>Refresh monitoring</button><h2 className="text-xl font-bold">Deletion requests</h2><p>Verify the request, resolve incident cases, and check retention obligations before completing. This action cannot be undone. Media is made inaccessible; storage and backups require retention cleanup.</p>{state?.privacy.map(r => <article key={r.userId} className="rounded border bg-white p-4"><p>{r.userId} · {r.status}</p>{r.status === "pending" && <button disabled={busy} onClick={() => { const confirmation = prompt("This removes the login and anonymizes operational data. Type ANONYMIZE AND DELETE LOGIN to continue."); if (confirmation === "ANONYMIZE AND DELETE LOGIN") void action({ action: "delete_account", userId: r.userId, confirmation }); }}>Complete account deletion</button>}</article>)}<h2 className="text-xl font-bold">Latest notification deliveries</h2><p>Sent means accepted by the provider, not confirmed read. Configure the notification worker to run every minute. Retries are at-least-once and may produce duplicate messages.</p>{state?.deliveries.map(d => <article key={d.id} className="rounded border bg-white p-4"><p>#{d.id} · {d.channel} · {d.status} · {d.attempts} attempts</p><p>{d.lastError}</p>{d.status === "failed" && <button disabled={busy} onClick={() => action({ action: "retry", id: d.id })}>Retry delivery</button>}</article>)}<p>Showing the latest 100 records in each section.</p></section>;
}
