"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
export function PrivacyControls() {
  const [state, setState] = useState<{ deletion: { status: string } | null; images: { key: string }[] } | null>(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  async function load() { const r = await fetch("/api/privacy"), d = await r.json(); if (!r.ok) throw new Error(d.error); setState(d); }
  // load only updates state after its network request resolves.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load().catch(e => setMessage(e.message)); }, []);
  async function action(data: unknown) { setBusy(true); try { const r = await fetch("/api/privacy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); setMessage("Privacy request saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Request failed."); } finally { setBusy(false); } }
  return <main className="mx-auto grid max-w-2xl gap-6 p-6"><Link href="/settings">← Settings</Link><h1 className="text-3xl font-bold">Privacy & your data</h1><p role="status">{message}</p><a className="underline" href="/api/privacy?export=1">Download your personal data (JSON)</a><section><h2 className="text-xl font-bold">Withdraw photo consent</h2><p>Photos become unavailable immediately, and related posts return to moderation. Previously downloaded copies cannot be recalled. Server file cleanup and backup retention are handled by your operator.</p>{state?.images.map(photo => <div key={photo.key} className="my-3 flex flex-wrap gap-3"><a href={"/api/media/" + photo.key} target="_blank" rel="noreferrer">View uploaded photo</a><button disabled={busy} onClick={() => { if (confirm("Remove this photo from FoodBridge and withdraw consent?")) void action({ action: "withdraw_photo", key: photo.key }); }}>Withdraw consent</button></div>)}</section><section><h2 className="text-xl font-bold">Delete account</h2><p>Finish or cancel active pickups first. An administrator reviews your request and resolves outstanding reports. Completion removes your login and anonymizes operational records. Aggregate donation history and pseudonymous audit records remain; backups follow the operator’s retention policy.</p>{state?.deletion?.status === "pending" ? <><p>Your deletion request is pending.</p><button disabled={busy} onClick={() => action({ action: "cancel_deletion" })}>Cancel deletion request</button></> : <form className="mt-4 grid gap-3" onSubmit={e => { e.preventDefault(); void action({ action: "request_deletion", confirmation: new FormData(e.currentTarget).get("confirmation") }); }}><label>Type DELETE MY ACCOUNT<input name="confirmation" required className="mt-2 w-full border p-3" autoComplete="off" /></label><button disabled={busy} className="rounded bg-red-800 p-3 text-white">Request account deletion</button></form>}</section></main>;
}
